src/Entity/User.php
<?php

namespace App\Entity;

use Timestamps;
use Assert\Timestamp;
use PhpParser\Node\Expr\New_;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\TimeStampableTrait;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
// use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;




// #[ORM\HasLifecycleCallbacks()]

#[ORM\Entity(repositoryClass: UserRepository::class)]
// #[Gedmo\Timestampable()]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 10)]
    private ?string $phone = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    // ::::::::::::::::::::::::::::::::::::

    // #[ORM\Column]
    // private ?\DateTime $created_at = null;

    // #[ORM\PrePersist]
    // public function  OnPrePersist()
    // {
    //     $this->created_at = new \DateTime('now');
    // }

    // #[ORM\Column]
    // private ?\DateTime $updated_at = null;

    // #[ORM\PreUpdate]
    // public function OnPreUpdate()
    // {
    //     $this->updated_at = new \DateTime('now');
    // }

    // ::::::::::::::::::::::::

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Program::class)]
    private Collection $programs;


    public function __construct()
    {
        $this->programs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Program>
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(Program $program): static
    {
        if (!$this->programs->contains($program)) {
            $this->programs->add($program);
            $program->setUser($this);
        }

        return $this;
    }

    public function removeProgram(Program $program): static
    {
        if ($this->programs->removeElement($program)) {
            // set the owning side to null (unless already changed)
            if ($program->getUser() === $this) {
                $program->setUser(null);
            }
        }

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    // public function getCreatedAt(): ?\DateTimeInterface
    // {
    //     return $this->created_at;
    // }

    // public function setCreatedAt(\DateTimeInterface $created_at): static
    // {
    //     $this->created_at = $created_at;
    //     // $this->created_at = $created_at(new \DateTimeImmutable('now'));
    //     return $this;
    // }

    // public function getUpdatedAt(): ?\DateTimeInterface
    // {
    //     return $this->updated_at;
    // }

    // public function setUpdatedAt(\DateTimeInterface $updated_at): static
    // {
    //     $this->updated_at = $updated_at;

    //     return $this;
    // }

    public function __toString()
    {
        return $this->getLastname() . " " . $this->getFirstname();
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/connexion', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_program_new');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!
{% endblock %}

{% block body %}
	<div class="container mt-5 mb-5 p-5 bg-white" style="box-shadow: 1px 2px 8px 1px ;">
		<form method="post">
			{% if error %}
				<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
			{% endif %}

			{% if app.user %}
				<div class="mb-3">
					You are logged in as
					{{ app.user.userIdentifier }},
					<a href="{{ path('app_logout') }}">Logout</a>
				</div>
			{% endif %}

			<h1 class=" text-center h3 mb-3 font-weight-normal">Vous êtes déjà inscrit ! connectez vous</h1>
			<div class="form-outline mb-4">
				<label class="form-label" for="inputEmail">Email</label>
				<input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
			</div>
			<div class="form-outline mb-4">
				<label class="form-label" for="inputPassword">Password</label>
				<input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
			</div>

			{# ///////////////////////////////////////// #}
			<!-- 2 column grid layout for inline styling -->
			<div class="row ">
				<div
					class="col-6 me-0">
					<!-- Checkbox -->
					<div class="form-check">
						<input class="form-check-input" type="checkbox" value="" id="form2Example31" checked/>
						<label class="form-check-label" for="form2Example31">
							Se souvenir de moi
						</label>
					</div>
				</div>

				{# <div
													class="col-6">
													<!-- Simple link -->
													<a href="#!">Mot de passe oublié?</a>
												</div> #}
			</div>

			{# //////////////////////////////////////////// #}
			<input
			type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

			{#
																																																																																									        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
																																																																																									        See https://symfony.com/doc/current/security/remember_me.html
																																																																																									
																																																																																									        <div class="checkbox mb-3">
																																																																																									            <label>
																																																																																									                <input type="checkbox" name="_remember_me"> Remember me
																																																																																									            </label>
																																																																																									        </div>
																																																																																									    #}

			<div class="d-flex justify-content-center mt-5">
				<button class="btn btn-dark btn-lg" type="submit">
					Se connecter
				</button>
			</div>
		</form>
	</div>
{% endblock %}