src/Entity/SessionSport.php
<?php

namespace App\Entity;

use App\Repository\SessionSportRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionSportRepository::class)]
class SessionSport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    // #[ORM\Column]
    // private ?\DateTimeImmutable $created_at = null;

    // #[ORM\Column]
    // private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'sessionSports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Program $program = null;

    #[ORM\OneToMany(mappedBy: 'sessionSport', targetEntity: ExerciceSessionSport::class)]
    private Collection $exerciceSessionSports;

    public function __construct()
    {
        $this->exerciceSessionSports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    // public function getCreatedAt(): ?\DateTimeImmutable
    // {
    //     return $this->created_at;
    // }

    // public function setCreatedAt(\DateTimeImmutable $created_at): static
    // {
    //     $this->created_at = $created_at;

    //     return $this;
    // }

    // public function getUpdatedAt(): ?\DateTimeImmutable
    // {
    //     return $this->updated_at;
    // }

    // public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    // {
    //     $this->updated_at = $updated_at;

    //     return $this;
    // }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): static
    {
        $this->program = $program;

        return $this;
    }

    /**
     * @return Collection<int, ExerciceSessionSport>
     */
    public function getExerciceSessionSports(): Collection
    {
        return $this->exerciceSessionSports;
    }

    public function addExerciceSessionSport(ExerciceSessionSport $exerciceSessionSport): static
    {
        if (!$this->exerciceSessionSports->contains($exerciceSessionSport)) {
            $this->exerciceSessionSports->add($exerciceSessionSport);
            $exerciceSessionSport->setSessionSport($this);
        }

        return $this;
    }

    public function removeExerciceSessionSport(ExerciceSessionSport $exerciceSessionSport): static
    {
        if ($this->exerciceSessionSports->removeElement($exerciceSessionSport)) {
            // set the owning side to null (unless already changed)
            if ($exerciceSessionSport->getSessionSport() === $this) {
                $exerciceSessionSport->setSessionSport(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getStartDate() . ' ' . $this->getEndDate();
    }
}

src/Entity/Traits.php
<?php

namespace App\Entity\Traits;

use App\Repository\TraitsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DateTime;
use DateTimeInterface;
use Exception;


#[ORM\Entity(repositoryClass: TraitsRepository::class)]
/**
 * Trait TimeStampableTrait
 * @package App\Entity\Trait
 */
trait TimeStampableTrait
{

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;


    /**
     * 
     * @return DateTimeInterface|null
     * @throws Exception
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at ?? new DateTime();
    }


    /**
     * @param DateTimeInterface $created_at
     * @return $this
     */
    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * 
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at ?? new DateTime();
    }

    /**
     * @param DateTimeInterface $updated_at
     * @return $this
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateTimestamps(): void
    {
        $now = new DateTime();
        $this->setUpdatedAt($now);
        if ($this->getId() === null) {
            $this->setCreatedAt($now);
        }
    }
}

src/Form/SessionSportType.php
<?php

namespace App\Form;

use App\Entity\Program;
use App\Entity\SessionSport;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionSportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date', DateTimeType::class, [
                'label' => 'Date de début',
                'date_widget' => 'single_text'
            ])
            ->add('end_date', DateTimeType::class, [
                'label' => 'Date de fin',
                'date_widget' => 'single_text'
            ])
            // ->add('created_at')
            // ->add('updated_at')
            ->add('program', EntityType::class, [
                'class' => Program::class,
                'choice_label' => 'name',
                'label' => 'Programme',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SessionSport::class,
        ]);
    }
}

src/Controller/SessionSportController.php
<?php

namespace App\Controller;

use App\Entity\SessionSport;
use App\Form\SessionSportType;
use App\Repository\SessionSportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/session/sport')]
class SessionSportController extends AbstractController
{
    #[Route('/', name: 'app_session_sport_index', methods: ['GET'])]
    public function index(SessionSportRepository $sessionSportRepository): Response
    {
        return $this->render('session_sport/index.html.twig', [
            'session_sports' => $sessionSportRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_session_sport_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SessionSportRepository $sessionSportRepository): Response
    {
        $sessionSport = new SessionSport();
        $form = $this->createForm(SessionSportType::class, $sessionSport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionSportRepository->save($sessionSport, true);

            return $this->redirectToRoute('app_session_sport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session_sport/new.html.twig', [
            'session_sport' => $sessionSport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_sport_show', methods: ['GET'])]
    public function show(SessionSport $sessionSport): Response
    {
        return $this->render('session_sport/show.html.twig', [
            'session_sport' => $sessionSport,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_session_sport_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SessionSport $sessionSport, SessionSportRepository $sessionSportRepository): Response
    {
        $form = $this->createForm(SessionSportType::class, $sessionSport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionSportRepository->save($sessionSport, true);

            return $this->redirectToRoute('app_session_sport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session_sport/edit.html.twig', [
            'session_sport' => $sessionSport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_sport_delete', methods: ['POST'])]
    public function delete(Request $request, SessionSport $sessionSport, SessionSportRepository $sessionSportRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sessionSport->getId(), $request->request->get('_token'))) {
            $sessionSportRepository->remove($sessionSport, true);
        }

        return $this->redirectToRoute('app_session_sport_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/session_sport/_delete_form.html.twig
<form method="post" action="{{ path('app_session_sport_delete', {'id': session_sport.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer cette session de sportt?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session_sport.id) }}">
	<button class="btn btn-danger mt-4">Supprimer</button>
</form>

templates/session_sport/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-dark me-2" style="width:150px;">{{ button_label|default('Sauvgarder') }}</button>
{{ form_end(form) }}

templates/session_sport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SessionSport
{% endblock %}

{% block body %}
	<div class="container mt-5 mb-5 p-5 bg-white" style="box-shadow: 1px 2px 8px 1px gray;">

		<h1>Edit SessionSport</h1>

		{{ include('session_sport/_form.html.twig', {'button_label': 'Update'}) }}

		<a href="{{ path('app_session_sport_index') }}">back to list</a>

		{{ include('session_sport/_delete_form.html.twig') }}
	</div>
{% endblock %}

templates/session_sport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SessionSport index
{% endblock %}

{% block body %}
	<div class="container mt-5 mb-5 p-5 bg-white" style="box-shadow: 1px 2px 8px 1px gray;">

		<h1>SessionSport index</h1>

		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Start_date</th>
					<th>End_date</th>
					<th>Created_at</th>
					<th>Updated_at</th>
					<th>actions</th>
				</tr>
			</thead>
			<tbody>
				{% for session_sport in session_sports %}
					<tr>
						<td>{{ session_sport.id }}</td>
						<td>{{ session_sport.startDate ? session_sport.startDate|date('Y-m-d H:i:s') : '' }}</td>
						<td>{{ session_sport.endDate ? session_sport.endDate|date('Y-m-d H:i:s') : '' }}</td>
						<td>{{ session_sport.createdAt ? session_sport.createdAt|date('Y-m-d H:i:s') : '' }}</td>
						<td>{{ session_sport.updatedAt ? session_sport.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
						<td>
							<a href="{{ path('app_session_sport_show', {'id': session_sport.id}) }}">show</a>
							<a href="{{ path('app_session_sport_edit', {'id': session_sport.id}) }}">edit</a>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="6">no records found</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<a href="{{ path('app_session_sport_new') }}">Create new</a>
	</div>
{% endblock %}

templates/session_sport/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SessionSport
{% endblock %}

{% block body %}
	<div class="container  mt-5 mb-5 p-5 bg-white" style="box-shadow: 1px 2px 8px 1px gray;">
		<h1 class="mb-5">Créer une nouvelle session de Sport</h1>

		{{ include('session_sport/_form.html.twig') }}

		<a href="{{ path('app_session_sport_index') }}">Retour à la liste</a>
	</div>
{% endblock %}

templates/session_sport/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SessionSport
{% endblock %}

{% block body %}
	<div class="container mt-5 mb-5 p-5 bg-white" style="box-shadow: 1px 2px 8px 1px gray;">

		<h1>SessionSport</h1>

		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ session_sport.id }}</td>
				</tr>
				<tr>
					<th>Start_date</th>
					<td>{{ session_sport.startDate ? session_sport.startDate|date('Y-m-d H:i:s') : '' }}</td>
				</tr>
				<tr>
					<th>End_date</th>
					<td>{{ session_sport.endDate ? session_sport.endDate|date('Y-m-d H:i:s') : '' }}</td>
				</tr>
				<tr>
					<th>Created_at</th>
					<td>{{ session_sport.createdAt ? session_sport.createdAt|date('Y-m-d H:i:s') : '' }}</td>
				</tr>
				<tr>
					<th>Updated_at</th>
					<td>{{ session_sport.updatedAt ? session_sport.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
				</tr>
			</tbody>
		</table>

		<a href="{{ path('app_session_sport_index') }}">back to list</a>

		<a href="{{ path('app_session_sport_edit', {'id': session_sport.id}) }}">edit</a>

		{{ include('session_sport/_delete_form.html.twig') }}
	</div>
{% endblock %}